### ISSUE TITLE
idea: 窗口拖动

### ISSUE THREAD

**Issue by Fromsko** [HEX9CF/CupidConnector#4]
> 不知为何：项目文档和代码排版总有一种说不出的美感，可能就是非常对称吧。

## Idea

可以针对如下区域设置窗口拖动，并对 App 标题文字选中进行移除，或许会更 ok 一些。

![image](https://github.com/user-attachments/assets/136c0757-dc3d-4cce-8746-6440136db18d)

**Comment by HEX9CF** [comment]
感谢@Fromsko的反馈！

我们会将这个建议纳入后续的开发计划中，如果有更多想法或建议，欢迎继续交流！

**Comment by ArtdragonXoX** [comment]
https://github.com/HEX9CF/CupidConnector/pull/3
该pr已提交拖动功能
